### ISSUE TITLE
Discrepancy in Loss Function Sign Between Code and Paper

### ISSUE THREAD

**Issue by edwardsandoval26** [Dandy5721/GeoNet4Net#1]
Dear Tingting Dan,

I hope this message finds you well. I have been carefully reviewing the code implementation and comparing it with the loss function described in your paper, and I have noticed a small discrepancy that I would like to bring to your attention.

In the code, the sign in the second term of the loss function appears to be different from what is outlined in the paper. Specifically, while the paper's loss function aims to minimize the similarity between different groups, the negative sign in the code would mean that it is minimizing the negative of the similarity, meaning the maximization of the similarity between different groups. It is possible that I may have misunderstood something, but I wanted to highlight this difference to ensure that everything aligns as intended.

Could you please clarify if this is an intentional adjustment or if there might be an error?

Thank you very much for your time and assistance.

Best regards,

Edward Sandoval

![image](https://github.com/user-attachments/assets/4ca30390-2724-48e4-a207-aab8f28a60c9)
![image](https://github.com/user-attachments/assets/453cd452-38a3-40fb-b71d-1695a64a64d8)

**Comment by Dandy5721** [comment]
Dear, Edward,

     Thanks for noting that, due to the code was recently organized, I have checked the local code, there may have been some carelessness and confusion with other codes. Thank you for your attention, I have corrected the code.
     
     Best,
     Tingting

**Comment by Dandy5721** [comment]
> Dear Tingting Dan,
> 
> I hope this message finds you well. I have been carefully reviewing the code implementation and comparing it with the loss function described in your paper, and I have noticed a small discrepancy that I would like to bring to your attention.
> 
> In the code, the sign in the second term of the loss function appears to be different from what is outlined in the paper. Specifically, while the paper's loss function aims to minimize the similarity between different groups, the negative sign in the code would mean that it is minimizing the negative of the similarity, meaning the maximization of the similarity between different groups. It is possible that I may have misunderstood something, but I wanted to highlight this difference to ensure that everything aligns as intended.
> 
> Could you please clarify if this is an intentional adjustment or if there might be an error?
> 
> Thank you very much for your time and assistance.
> 
> Best regards,
> 
> Edward Sandoval
> 
> ![image](https://private-user-images.githubusercontent.com/85711429/348858550-4ca30390-2724-48e4-a207-aab8f28a60c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg2NDgsIm5iZiI6MTcyMTEzODM0OCwicGF0aCI6Ii84NTcxMTQyOS8zNDg4NTg1NTAtNGNhMzAzOTAtMjcyNC00OGU0LWEyMDctYWFiOGYyOGE2MGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNGQyYjUwMDMyNTk4MTM1YzcxZDZhYTM5Nzg2ZjdlNTgwMzRiNmE5MTc3YTdjMjFhNzRiNTUyYTU4NDJmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zAeCNSExzO0Jp_wXSM8hmFhEFlAU0w0NzTdiPiB7Irw) ![image](https://private-user-images.githubusercontent.com/85711429/348858618-453cd452-38a3-40fb-b71d-1695a64a64d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg2NDgsIm5iZiI6MTcyMTEzODM0OCwicGF0aCI6Ii84NTcxMTQyOS8zNDg4NTg2MTgtNDUzY2Q0NTItMzhhMy00MGZiLWI3MWQtMTY5NWE2NGE2NGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzBjMmE4ZDViZjc3MmQ1NDU0YzAxOGVmN2FlNDE1Y2UxOWZjOTZhZWRhYzQ1NDZkM2I4MmJmZWQ0MTAwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLJbi-GzQu-V0DplJtFRDIvIHr0BvCSvolL4UvzDg20)



> Dear, Edward,
> 
> ```
>  Thanks for noting that, due to the code was recently organized, I have checked the local code, there may have been some carelessness and confusion with other codes. Thank you for your attention, I have corrected the code.
>  
>  Best,
>  Tingting
> ```

Dear, Edward,

 Thanks for noting that, due to the code was recently organized, I have checked the local code, there may have been some carelessness and confusion with other codes. Thank you for your attention, I have corrected the code.
 
 Best,
 Tingting

**Comment by edwardsandoval26** [comment]
Dear Tingting Dan,

I appreciate your attention to detail and your efforts to ensure everything is accurate and aligned with the paper. I have reviewed the updated code, and it now aligns perfectly with the loss function described in your paper. I believe this resolves the issue completely.

Best regards,

Edward Sandoval

**Comment by edwardsandoval26** [comment]
Dear Tingting Dan,

I appreciate your attention to detail and your efforts to ensure everything is accurate and aligned with the paper. I have reviewed the updated code, and it now aligns perfectly with the loss function described in your paper. I believe this resolves the issue completely.

Best regards,

Edward Sandoval
